const nadoStrategies = require('./nado-strategies.js')
const cazaStrategies = require('./caza-strategies.js')
const comportamientoStrategies = require('./comportamiento-strategies.js')
const Tiburon = require('./Tiburon.js')
// Prueba de funcionamiento del código.
const tiburonBlanco = new Tiburon(5, 'Gris oscuro', 500)

tiburonBlanco.nado()
tiburonBlanco.caza()
tiburonBlanco.comportamiento()
tiburonBlanco.setNadoStrategy(nadoStrategies.nadoBajoStrategy)
tiburonBlanco.nado()
tiburonBlanco.setCazaStrategy(cazaStrategies.cazoCarronaStrategy)
tiburonBlanco.caza()
tiburonBlanco.setComportamientoStrategy(comportamientoStrategies.comportamientoCuriosoStrategy)
tiburonBlanco.comportamiento()